const Map<String, String> ar = {
  "STEP 1": "الخطوة 1",
  "STEP 2": "الخطوة 2",
  "STEP 3": "الخطوة 3",
  "STEP 4": "الخطوة 4",
  "Get Started": "البدء",
  "Yalla Farha": "يلا فرحة",
  "YOU ARE FOUR STEPS AWAY FROM YOUR HAPPINESS": "أنت على بعد أربع خطوات من سعادتك",
  "Email - Username": "البريد الإكتروني - إسم المستخدم",
  "Password": "كلمة المرور",
  "Enter your email": "أدخل البريد الإكتروني",
  "Enter your password": "أدخل كلمة المرور",
  "Forgot your password ?": "هل نسيت كلمة المرور ؟",
  "Log in": "تسجيل الدخول",
  "Sign in with": "سجل عن طريق",
  "Don't have an account ?": "ليس لديك حساب ؟",
  "OR": "أو",
  "Sign up now": "أنشئ حساب الآن",
  "Full name": "الإسم الكامل",
  "Username": "إسم المستخدم",
  "Email": "البريد الإلكتروني",
  "Confirm password": "تأكيد كلمة المرور",
  "Enter your name": "أدخل إسمك",
  "SIGN UP": "إنشاء حساب",
  "Already have an account ?": "هل لديك حساب بالفعل ؟",
  "Sign in": "تسجيل الدخول",
  'Payment method': 'طرق الدفع',
  'Amount': 'المبلغ',
  'Card number': 'رقم البطاقة',
  'ccv': 'ccv',
  'End date': 'تاريخ الإنتهاء',
  'Message': 'الرسالة',
  "Send now": "إرسال الآن",
  "Field is required": "هذا الحقل مطلوب",
  'Select Language': 'إختيار اللغة',
  "CREATE YOUR ACCOUNT": "أنشئ حسابك",
  "CHOOSE YOUR OCCASION": "إختر مناسبتك",
  "PICK YOUR ITEMS": "أضف المنتجات",
  "SHARE YOUR WISHLIST": "شارك قائمتك",
  "invalid email": "بريد إلكتروني خاطئ",
  "invalid username": "إسم مستخدم خاطئ",
  "Confirm your password": "قم بتأكيد كلمة المرور",
  "password does not match": "كلمة المرور غير متطابقة",
  "Sign up": "أنشئ حساب",
  "Enter your username": "أدخل إسم المستخدم",
  "password must be more than 5 characters": "كلمة المرور يجب ان تكون أكثر من 5 رموز",
  "OCCASIONS": "المناسبات",
  "OUR SUPPLIERS": "موردينا",
  "CATEGORIES": "التصنيفات",
  "View all": "مشاهدة الكل",
  "Our mission is to support and achieve social solidarity and facilitating the process of the people getting married, having weddings and other happy events by taking advantage of the development of technology in order to transform": "مهمتنا هي دعم وتحقيق التكافل الاجتماعي وتسهيل عملية زواج الناس وإقامة حفلات الزفاف وغيرها من المناسبات السعيدة من خلال الاستفادة من تطور التكنولوجيا من أجل التحول",
  "WHO WE ARE": "من نحن",
  "Read more": "اقرأ أكثر",
  "Our Happiness Stories": "قصص السعادة لدينا",
  "Home": "الرئيسية",
  "About Yalla Farha": "حول يلا فرحة",
  "Account": "الحساب",
  "Language": "اللغة",
  "Notifications": "الإشعارات",
  "Logout": "تسجيل الخروج",
  "Follow Us": "تابعنا",
  "Privacy policy": "سياسة الخصوصية",
  "Terms & Conditions": "الشروط والأحكام",
  "Refund policy": "سياسة الاسترجاع",
  "Contact us": "تواصل معنا",
  "Become a supplier": "أصبح موردا",
  "BE A PART OF THEIR HAPPINESS": "كن جزءًا من سعادتهم",
  "Occasions": "المناسبات",
  "Categories": "التصنيفات",
  "My orders": "طلباتي",
  "Phone number": "رقم الهاتف",
  "Send": "إرسال",
  "Select": "إختيار",
  "Gallery": "الأستديو",
  "Camera": "الكاميرا",
  "Chose image": "إختر صورة",
  "Occasion image": "صورة المناسبة",
  "Occasion": "المناسبة",
  "Make wishlist": "إنشاء قائمة الرغبات",
  "Start date": "تاريخ البدء",
  "End Date": "تاريخ الانتهاء",
  "Occasion title": "عنوان المناسبة",
  "Create": "إنشاء",
  "Category": "القائمة",
  "Filter": "الفلتر",
  "View": "تصفح",
  "Add": "إضافة",
  "Pay now": "إدفع الآن",
  "Start": "البداية",
  "Backers": "الداعمين",
  "Days left": "يوم متبقي",
  "Total fund needed": "المبلغ الإجمالي المطلوب",
  "Collected": "المحصل",
  "Share": "نشر",
  "We’re happy to Share your experience with everyone!": "يسعدنا مشاركة تجربتك مع الجميع!",
  "Edit profile": "تعديل الحساب",
  "My occasions": "مناسباتي",
  "My review for Yalla Farha": "تقييمي ليلا فرحة",
  "Review summary": "ملخص المراجعة",
  "Overall rating*": "التقييم العام*",
  "Click to rate!": "أنقر للتقييم!",
  "Example: The App is very nice and the concept is amazing.": "مثال: التطبيق جميل جدًا والمبدأ مذهل.",
  "Review*": "تقييم*",
  "Consider: Why you choose Yalla Farha? What do you like in the App? Who do you recommend Yalla Farha?": "ضع في اعتبارك: لماذا اخترت يلا فرحة؟ ماذا تحب في التطبيق؟ بمن تنصح يلا فرحة؟",
  "Attach image": "إرفاق صورة",
  "Attach video": "إرفاق فيديو",
  "You can upload up to 5 photos": "يمكنك إرفاق ما يصل إلى 5 صور",
  "Example: Ali (Max 20 Characters).": "مثال: علي (بحد أقصى 20 حرفًا).",
  "Name*": "الإسم*",
  "Email*": "البريد الإلكتروني*",
  "Example: Ali@abc.com.": "مثال: Ali@abc.com",
  "Occasion name: wedding": "إسم المناسبة: زفاف",
  "Post review": "نشر التقييم",
  "Occasion*": "المناسبة*",
  "I have read the Terms & Conditions and agree to them. To find out more about our privacy policy please refer to the Yalla Farha Privacy Notice Your review may be published on other websites advertising this app.": "لقد قرأت الشروط والأحكام وأوافق عليها. لمعرفة المزيد حول سياسة الخصوصية الخاصة بنا ، يرجى الرجوع إلى إشعار الخصوصية في Yalla Farha ، قد يتم نشر تعليقك على مواقع الويب الأخرى التي تعلن عن هذا التطبيق.",
  "You must accept terms and conditions to continue": "يجب عليك قبول الشروط والأحكام للمتابعة",
  "You must upload image or video in review field": "يجب تحميل الصورة أو الفيديو في حقل المراجعة",
  "invalid password": "كلمة مرور خاطئة",
  "You must determine a starting date first": "يجب عليك تحديد تاريخ البدء أولا",
  "End": "النهاية",
  "Paypal": "باي بال",
  "Credit card": "بطاقة إئتمان",
  "Zain cash": "زين كاش",
  "Orange money": "محفظة أورانج",
  "Terms and conditions": "الشروط والأحكام",
  "Enter your email and we will send you a link to reset your password.": "أدخل بريدك الإلكتروني وسنرسل لك رابطًا لإعادة تعيين كلمة المرور الخاصة بك.",
  "Forgot password": "إعادة تعيين كلمة المرور",
  "Back": "الرجوع",
  "My cart": "سلة التسوق",
  "Delete": "حذف",
  "Would you like to delete this item?": "هل ترغب في حذف هذا العنصر؟",
  "Product info": "معلومات المنتج",
  "Add to cart": "إضافة الى السلة",
  "JD": "د.أ",
  "Checkout": "الدفع",
  "Total price": "السعر الكلي",
  "Save": "حفظ",
  "Open": "تصفح",
  "Explore more": "تصفح المزيد",
  "Coming soon": "قريبا",
  "Details": "التفاصيل",
  "Quantity": "الكمية",
  "Added": "تم الإضافة",
  "Processing": "قيد اللإنتظار",
  "Delivered": "تم إستلامه",
  "Ali Kanaan": "علي كنعان",
  "Founder CEO": "الرئيس التنفيذي المؤسس",
  "Verification Code": "رمز التحقق",
  "Enter the code that has been sent to your phone number.": "أدخل الرمز الذي تم إرساله إلى رقم هاتفك.",
  "Enter the verification code": "أدخل رمز التحقق",
  "You have paid successfully": "تمت عملية الدفع بنجاح",
  "Your request was sent successfully": "تم إرسال طلبك بنجاح",
  "Your review has been sent successfully": "تم إرسال تقييمك بنجاح",
  "Product Added": "تم إضافة المنتج",
  "View Cart": "سلة المشتريات",
  "Payment completed successfully": "تمت عملية الدفع بنجاح",
  "incorrect code": "رمز غير صحيح",
  "Skip": "تخطي",
  "Saved": "تم الحفظ",
  "image": "الصورة",
  "Link copied, send it to your friends to share your occasion": "تم نسخ الرابط وإرساله إلى أصدقائك لمشاركة مناسبتك",
  "Incorrect email or password": "بريد أو كلمة مرور غير صحيحة",
  "Email or username is already registered": "البريد الإلكتروني أو إسم المستخدم مسجل مسبقا",
  "Sign in to continue": "قم بتسجيل الدخول للمتابعة",
  "There are no previous orders": "لا يوجد طلبات سابقة",
  "Jo": "دينار",
  "Cart is empty": "السلة فارغة",
  "Choose payment method": "إختر طريقة الدفع",
  "Pay": "الدفع",
  "": "",
};
