const Map<String, String> en = {
  "STEP 1": "STEP 1",
  "STEP 2": "STEP 2",
  "STEP 3": "STEP 3",
  "STEP 4": "STEP 4",
  "Get Started": "Get Started",
  "Yalla Farha": "Yalla Farha",
  "YOU ARE FOUR STEPS AWAY FROM YOUR HAPPINESS": "YOU ARE FOUR STEPS AWAY FROM YOUR HAPPINESS",
  "Email - Username": "Email - Username",
  "Password": "Password",
  "Enter your email": "Enter your email",
  "Enter your password": "Enter your password",
  "Forgot your password ?": "Forgot your password ?",
  "Log in": "Log in",
  "Sign in with": "Sign in with",
  "Don't have an account ?": "Don't have an account ?",
  "OR": "OR",
  "Sign up now": "Sign up now",
  "Full name": "Full name",
  "Username": "Username",
  "Email": "Email",
  "Confirm password": "Confirm password",
  "Enter your name": "Enter your name",
  "Enter your username": "Enter your username",
  "invalid username": "invalid username",
  "SIGN UP": "SIGN UP",
  "Already have an account ?": "Already have an account ?",
  "Sign in": "Sign in",
  'Payment method': 'Payment method',
  'Amount': 'Amount',
  'Card number': 'Card number',
  'ccv': 'ccv',
  'End date': 'End date',
  'Message': 'Message',
  "Send now": "SEND NOW",
  "Field is required": "Field is required",
  'Select Language': 'Select Language',
  "CREATE YOUR ACCOUNT": "CREATE YOUR ACCOUNT",
  "CHOOSE YOUR OCCASION": "CHOOSE YOUR OCCASION",
  "PICK YOUR ITEMS": "PICK YOUR ITEMS",
  "SHARE YOUR WISHLIST": "SHARE YOUR WISHLIST",
  "invalid email": "invalid email",
  "Confirm your password": "Confirm your password",
  "password does not match": "password does not match",
  "Sign up": "Sign up",
  "password must be more than 5 characters": "password must be more than 5 characters",
  "OCCASIONS": "OCCASIONS",
  "OUR SUPPLIERS": "OUR SUPPLIERS",
  "CATEGORIES": "CATEGORIES",
  "View all": "View all",
  "Our mission is to support and achieve social solidarity and facilitating the process of the people getting married, having weddings and other happy events by taking advantage of the development of technology in order to transform": "Our mission is to support and achieve social solidarity and facilitating the process of the people getting married, having weddings and other happy events by taking advantage of the development of technology in order to transform",
  "WHO WE ARE": "WHO WE ARE",
  "Read more": "Read more",
  "Our Happiness Stories": "Our Happiness Stories",
  "Home": "Home",
  "About Yalla Farha": "About Yalla Farha",
  "Account": "Account",
  "Language": "Language",
  "Notifications": "Notifications",
  "Logout": "Logout",
  "Follow Us": "Follow Us",
  "Privacy policy": "Privacy policy",
  "Terms & Conditions": "Terms & Conditions",
  "Refund policy": "Refund policy",
  "Contact us": "Contact us",
  "Become a supplier": "Become a supplier",
  "BE A PART OF THEIR HAPPINESS": "BE A PART OF THEIR HAPPINESS",
  "Occasions": "Occasions",
  "Categories": "Categories",
  "My orders": "My orders",
  'Phone number': "Phone number",
  "Send": "Send",
  "Select": "Select",
  "Gallery": "Gallery",
  "Camera": "Camera",
  "Chose image": "Chose image",
  "Occasion image": "Occasion image",
  "Occasion": "Occasion",
  "Make wishlist": "Make wishlist",
  "Start date": "Start date",
  "End Date": "End Date",
  "Occasion title": "Occasion title",
  "Create": "Create",
  "Category": "Category",
  "Filter": "Filter",
  "View": "View",
  "Add": "Add",
  "Pay now": "Pay now",
  "Start": "Start",
  "Backers": "Backers",
  "Days left": "Days left",
  "Total fund needed": "Total fund needed",
  "Collected": "Collected",
  "Share": "Share",
  "We’re happy to Share your experience with everyone!": "We’re happy to Share your experience with everyone!",
  "Edit profile": "Edit profile",
  "My occasions": "My occasions",
  "My review for Yalla Farha": "My review for Yalla Farha",
  "Review summary": "Review summary",
  "Overall rating": "Overall rating*",
  "Click to rate!": "Click to rate!",
  "Example: The App is very nice and the concept is amazing.": "Example: The App is very nice and the concept is amazing.",
  "Review*": "Review*",
  "Consider: Why you choose Yalla Farha? What do you like in the App? Who do you recommend Yalla Farha?": "Consider: Why you choose Yalla Farha? What do you like in the App? Who do you recommend Yalla Farha?",
  "Attach image": "Attach image",
  "Attach video": "Attach video",
  "You can upload up to 5 photos": "You can upload up to 5 photos",
  "Example: Ali (Max 20 Characters).": "Example: Ali (Max 20 Characters).",
  "Name*": "Name*",
  "Email*": "Email*",
  "Example: Ali@abc.com.": "Example: Ali@abc.com.",
  "Occasion name: wedding": "Occasion name: wedding",
  "I have read the Terms & Conditions and agree to them. To find out more about our privacy policy please refer to the Yalla Farha Privacy Notice Your review may be published on other websites advertising this app.": "I have read the Terms & Conditions and agree to them. To find out more about our privacy policy please refer to the Yalla Farha Privacy Notice Your review may be published on other websites advertising this app.",
  "Post review": "Post review",
  "Occasion*": "Occasion*",
  "You must accept terms and conditions to continue": "You must accept terms and conditions to continue",
  "You must upload image or video in review field": "You must upload image or video in review field",
  "invalid password": "invalid password",
  "You must determine a starting date first": "You must determine a starting date first",
  "End": "End",
  "Paypal": "Paypal",
  "Credit card": "Credit card",
  "Zain cash": "Zain cash",
  "Orange money": "Orange money",
  "Terms and conditions": "Terms and conditions",
  "Enter your email and we will send you a link to reset your password.": "Enter your email and we will send you a link to reset your password.",
  "Forgot password": "Forgot password",
  "Back": "Back",
  "My cart": "My cart",
  "Delete": "Delete",
  "Would you like to delete this item?": "Would you like to delete this item?",
  "Product info": "Product info",
  "Add to cart": "Add to cart",
  "JD": "JD",
  "Checkout": "Checkout",
  "Total price": "Total price",
  "Save": "Save",
  "Open": "Open",
  "Explore more": "Explore more",
  "Coming soon": "Coming soon",
  "Details": "Details",
  "Quantity": "Quantity",
  "Added": "Added",
  "Processing": "Processing",
  "Delivered": "Delivered",
  "Ali Kanaan": "Ali Kanaan",
  "Founder CEO": "Founder CEO",
  "Verification Code": "Verification Code",
  "Enter the code that has been sent to your phone number.": "Enter the code that has been sent to your phone number.",
  "Enter the verification code": "Enter the verification code",
  "You have paid successfully": "You have paid successfully",
  "Your request was sent successfully": "Your request was sent successfully",
  "Your review has been sent successfully": "Your review has been sent successfully",
  "Product Added": "Product Added",
  "View Cart": "View Cart",
  "Payment completed successfully": "Payment completed successfully",
  "incorrect code": "incorrect code",
  "Skip": "Skip",
  "Saved": "Saved",
  "image": "image",
  "Link copied, send it to your friends to share your occasion": "Link copied, send it to your friends to share your occasion",
  "Incorrect email or password": "Incorrect email or password",
  "Email or username is already registered": "Email or username is already registered",
  "Sign in to continue": "Sign in to continue",
  "There are no previous orders": "There are no previous orders",
  "Jo": "Jo",
  "Cart is empty": "Cart is empty",
  "Choose payment method": "Choose payment method",
  "Pay": "Pay",
  "": "",
};
